### ISSUE TITLE
Why the forked branch of vue

### ISSUE THREAD

**Issue by ericop** [DanielRosenwasser/typescript-vue-todomvc#1]
Hi Daniel,
This and the starter setup at https://github.com/Microsoft/TypeScript-Vue-Starter are really cool. Thanks for putting the time in to these to make them clear and easy for newbies!

So the question I have is why must we use your branch, at a specific commit of VueJS? Are these features that play nice with typescript coming to the master branch?  Having  built a production single page app in ember that was dependent on a side branch like this, I know it can be done, but when you need or want a new feature you have to play this weird self-patching game that's kind of a drag.  So I just wanted the scoop from you about why this is setup this way before I invest too deeply.

**Comment by ericop** [comment]
I found https://github.com/vuejs/vue-loader/issues/109#issuecomment-301151650 and saw above it where you asked questions to get your frozen branch functional. Seems like https://github.com/vuejs-templates needs an official setup for Typescript with https://vuejs.org/v2/guide/single-file-components.html . Feels like we are shooting at a moving target. I never was any good at DuckHunt 🦆 . 😃

**Comment by mythz** [comment]
I'm also trying to closely follow the progress on this, is there an open PR where we can track to see when your changes get merged into vue?

**Comment by ericop** [comment]
Daniel,
Looks like back on May 8th you were scheming to talk with @yyx990803 about how to make Vue 2.4 work with TypeScript shim free? https://github.com/octref/vetur/pull/94#issuecomment-299935258 . If that works out, in v.2.4 let us know so we can do a little jig 🕺 and send you and @yyx990803 a virtual high-five! Vue and TypeScript are getting more and more attention for the amazing things they are because of power-nerds like you guys doing great work, so keep it up, and may you find delight in your labors!

**Comment by DanielRosenwasser** [comment]
Hey guys, the PR is up at https://github.com/vuejs/vue/pull/5887

**Comment by ericop** [comment]
@DanielRosenwasser thank you for the update! All the labor and tricky decisions that went into this PR you've done is huge, so thanks! 

For those who stumble upon this, it looks like VueJS 2.5 might be the most likely future version which will get more canonical type usage. The real limiters on this getting into the VueJS 2.4 or 2.5 are [these](https://github.com/vuejs/vue/pull/5887#issuecomment-309201367):
- [x] Release of Typescript 2.4
- [ ] Update of `vue-class-component` , `vue-router` and `vuex` since they use `ComponentOptions`

**Comment by ericop** [comment]
The latest merge request is getting code reviewed at https://github.com/vuejs/vue/pull/6391

**Comment by ericop** [comment]
@DanielRosenwasser and @HerringtonDarkholme looks like through blood, sweat and tears you guys got this thing working in first rate order!
- https://medium.com/the-vue-point/vue-2-5-released-14bd65bf030b#559e
- https://github.com/vuejs/vue/releases/tag/v2.5.0 

Looks like https://vuejs.org/v2/guide/typescript.html covers the new approach well! **Thank you, thank you, as even [Evan You thanks you](https://medium.com/the-vue-point/upcoming-typescript-changes-in-vue-2-5-e9bd7e2ecf08#b2d2)**! :) Seriously, I'm very pumped up by this!

**Comment by DanielRosenwasser** [comment]
You're welcome! Super glad to see the enthusiasm. Keep me posted on how using it works out!

**Comment by ericop** [comment]
I plan to try it out on a clean new project once their is a [Typescript Template](https://github.com/vuejs-templates) for the [Vue CLI](https://github.com/vuejs/vue-cli) . And I'll let you know. My last big project I used Typescript and AngularJS (ng1.x) and I *really* liked what Typescript added. Now with [computed-properties](https://vuejs.org/v2/guide/computed.html#Computed-vs-Watched-Property) like I used to use back in Ember :hamster:, and [single-file-components](https://vuejs.org/v2/guide/typescript.html#Basic-Usage) I feel unstoppable :repeat: !
